export const examples = [
  'Quiero hacer una cena romántica para dos esta noche.',
  'Me apetece algo picante y sabroso para la cena.',
  'Necesito una receta rápida y fácil de desayuno para las mañanas ocupadas.',
  'Quiero impresionar a mis amigos con una receta de postre elegante.',
  'Tengo ganas de comida reconfortante, algo caliente y llenador.',
  'Quiero hacer una comida saludable y nutritiva para mi familia esta noche.',
  'Estoy organizando una fiesta y necesito ideas de aperitivos.',
  'Tengo un presupuesto ajustado y necesito algunas ideas de comidas económicas.',
  'Soy vegetariano y necesito algunas ideas de nuevas recetas para comidas ricas en proteínas.',
  'Tengo un montón de tomates, coliflor, patata y pepino que quiero usar.',
  'Quiero hacer un plato inspirado en una cultura diferente, pero no estoy seguro por dónde empezar.',
  'Estoy tratando de reducir los carbohidratos y necesito algunas ideas de recetas bajas en carbohidratos.',
  'Quiero hacer un pastel de cumpleaños especial para mi amigo, a quien le encanta el chocolate.',
  'Estoy tratando de incorporar más mariscos en mi dieta y necesito algunas ideas de recetas.',
  'Quiero hacer una pizza casera desde cero, pero necesito una receta para la masa.',
  'Estoy tratando de comer más comidas basadas en plantas y necesito algunas ideas de recetas veganas.',
  'Estoy en una dieta baja en grasas y necesito algunas ideas de recetas que aún sean sabrosas.',
  'Quiero hacer una receta que se pueda preparar fácilmente para la semana que viene.',
  'Quiero hacer una sopa de cebolla francesa clásica, pero no tengo caldo de carne.',
  'Tengo antojo de un pollo tikka masala, pero no tengo yogur para el marinado.',
  'Quiero hacer un pad thai tradicional, pero no tengo pasta de tamarindo.',
  'Tengo ganas de un guiso de carne abundante, pero no tengo vino tinto.',
  'Quiero hacer un hummus delicioso, pero no tengo pasta de tahini.',
]
