export default function getRandomRecipeQuery(language) {
  const recipeQueries = [
    'I want to make a romantic dinner for two tonight.',
    "I'm craving something spicy and flavorful for dinner.",
    'I need a quick and easy breakfast recipe for busy mornings.',
    'I want to impress my friends with a fancy dessert recipe.',
    "I'm in the mood for comfort food, something warm and filling.",
    'I want to make a healthy and nutritious meal for my family tonight.',
    "I'm hosting a party and need some appetizer ideas.",
    "I'm on a budget and need some cheap meal ideas.",
    "I'm a vegetarian and need some new recipe ideas for protein-rich meals.",
    'I have a bunch of tomatoes, cauliflower, potato and cucumber that I want to use up.',
    "I want to make a dish inspired by a different culture, but I'm not sure where to start.",
    "I'm trying to cut down on carbs and need some low-carb recipe ideas.",
    'I want to make a special birthday cake for my friend, who loves chocolate.',
    "I'm trying to incorporate more seafood into my diet and need some recipe ideas.",
    'I want to make a homemade pizza from scratch, but need a recipe for the dough.',
    "I'm trying to eat more plant-based meals and need some vegan recipe ideas.",
    "I'm on a low-fat diet and need some recipe ideas that are still flavorful.",
    'I want to make a recipe that can easily be meal prepped for the week ahead.',
    "I want to make a classic French onion soup, but I don't have any beef broth.",
    "I'm craving a chicken tikka masala, but I don't have any yogurt for the marinade.",
    "I want to make a traditional pad thai, but I don't have tamarind paste.",
    "I'm in the mood for a hearty beef stew, but I don't have any red wine.",
    "I want to make a delicious hummus, but I don't have tahini paste.",
  ]

  const recipeQueriesEs = [
    'Quiero hacer una cena romántica para dos esta noche.',
    'Me apetece algo picante y sabroso para la cena.',
    'Necesito una receta rápida y fácil de desayuno para las mañanas ocupadas.',
    'Quiero impresionar a mis amigos con una receta de postre elegante.',
    'Quiero hacer una comida saludable y nutritiva para mi familia esta noche.',
    'Estoy organizando una fiesta y necesito ideas de aperitivos.',
    'Tengo un presupuesto ajustado y necesito algunas ideas de comidas económicas.',
    'Soy vegetariano y necesito algunas ideas de nuevas recetas para comidas ricas en proteínas.',
    'Tengo un montón de tomates, coliflor, patata y pepino que quiero usar.',
    'Quiero hacer un plato inspirado en una cultura diferente, pero no estoy seguro por dónde empezar.',
    'Estoy tratando de reducir los carbohidratos y necesito algunas ideas de recetas bajas en carbohidratos.',
    'Quiero hacer un pastel de cumpleaños especial para mi amigo, a quien le encanta el chocolate.',
    'Estoy tratando de incorporar más mariscos en mi dieta y necesito algunas ideas de recetas.',
    'Quiero hacer una pizza casera desde cero, pero necesito una receta para la masa.',
    'Estoy tratando de comer más comidas basadas en plantas y necesito algunas ideas de recetas veganas.',
    'Estoy en una dieta baja en grasas y necesito algunas ideas de recetas que aún sean sabrosas.',
    'Quiero hacer una receta que se pueda preparar fácilmente para la semana que viene.',
    'Quiero hacer una sopa de cebolla francesa clásica, pero no tengo caldo de carne.',
    'Tengo antojo de un pollo tikka masala, pero no tengo yogur para el marinado.',
    'Quiero hacer un pad thai tradicional, pero no tengo pasta de tamarindo.',
    'Tengo ganas de un guiso de carne abundante, pero no tengo vino tinto.',
    'Quiero hacer un hummus delicioso, pero no tengo pasta de tahini.',
  ]

  const randomIndex = Math.floor(Math.random() * recipeQueries.length)
  return language === "es" ? recipeQueriesEs[randomIndex] : recipeQueries[randomIndex]
}
